import jsPDF from "jspdf";

export type ReceiptInput = {
  id: string;
  trace_id?: string | null;
  kind: string; // topup, transfer_in, transfer_out, payout, hold, release, fee...
  status?: string | null;
  amount_minor: number;
  currency: string;
  created_at: string;
  counterparty?: string | null;
  note?: string | null;
  balance_after_minor?: number | null;
};

const KIND_AR: Record<string, string> = {
  topup: "شحن محفظة",
  transfer_in: "استلام تحويل",
  transfer_out: "إرسال تحويل",
  payout: "سحب",
  hold: "حجز مبلغ",
  release: "تحرير حجز",
  fee: "عمولة",
  refund: "استرداد",
};

function fmt(minor: number, ccy: string) {
  return `${(minor / 100).toFixed(2)} ${ccy}`;
}

export function downloadWalletReceipt(r: ReceiptInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 56;

  doc.setFillColor(13, 148, 136); // teal
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Harraj Almashari — Receipt", W / 2, 38, { align: "center" });
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("IDEA BUSINESS — إيصال عملية محفظة", W / 2, 62, { align: "center" });

  y = 120;
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(KIND_AR[r.kind] ?? r.kind, W - 40, y, { align: "right" });
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y, W - 40, y);
  y += 24;

  const rows: [string, string][] = [
    ["Receipt / رقم العملية", r.id],
    ["Trace ID", r.trace_id || "—"],
    ["Type / النوع", `${KIND_AR[r.kind] ?? r.kind} (${r.kind})`],
    ["Status / الحالة", r.status ?? "completed"],
    ["Amount / المبلغ", fmt(r.amount_minor, r.currency)],
    ...(r.balance_after_minor != null ? [["Balance after / الرصيد بعد", fmt(r.balance_after_minor, r.currency)]] as [string, string][] : []),
    ...(r.counterparty ? [["Counterparty / الطرف الآخر", r.counterparty]] as [string, string][] : []),
    ["Date / التاريخ", new Date(r.created_at).toLocaleString("en-GB")],
    ...(r.note ? [["Note / ملاحظة", r.note]] as [string, string][] : []),
  ];

  doc.setFontSize(11);
  for (const [k, v] of rows) {
    doc.setFont("helvetica", "bold");
    doc.text(k, 40, y);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(String(v), W - 260);
    doc.text(lines, W - 40, y, { align: "right" });
    y += Math.max(18, lines.length * 14);
    if (y > 740) { doc.addPage(); y = 60; }
  }

  y += 20;
  doc.setDrawColor(220); doc.line(40, y, W - 40, y); y += 20;
  doc.setFontSize(9);
  doc.setTextColor(110);
  doc.text("This receipt is auto-generated by busniss.org wallet ledger. Hash-chained & immutable.", 40, y);
  y += 12;
  doc.text("هذا الإيصال صادر آلياً من سجل المحفظة في busniss.org — مرتبط بسلسلة هاش غير قابلة للتعديل.", 40, y);

  const safeId = r.id.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 40);
  doc.save(`receipt-${safeId}.pdf`);
}
